name: "Update kujira pairs"

on:
  schedule:
    - cron: "0 * * * *" # runs every 1 hour
  workflow_dispatch:
jobs:
  kujira_pairs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ".github/scripts"
    steps:
      - name: Checkout repository and branch
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          cache-dependency-path: './.github/scripts/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Upgrade kujira.js
        run: pnpm upgrade kujira.js

      - name: Run script to Get Pairs
        run: |
          ROOT_DIR=${{ github.workspace }} pnpm export-pairs
          
      - name: Check for changes
        id: diff
        run: |
          cd ${{ github.workspace }}
          git diff --quiet fin-pairs.json || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push changes
        if: steps.diff.outputs.changed == 'true'
        run: |
          cd ${{ github.workspace }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[bot] update pairs"
          git push
